### ISSUE TITLE
view use WeakReference store?

### ISSUE THREAD

**Issue by JakeWoki** [MaksTuev/ferro#2]
`MvpPresenter:

private V view;

public void attachView(V view) {
        this.view = view;
}

protected V getView() {
        return view;
}

public final void detachView() {
        view = null;
        onViewDetached();
}

instead of:

private WeakReference<V> view;

public void attachView(@NonNull V view) {
        this.view = new WeakReference<>(view);
}

@Nullable
protected V getView() {
        return view == null ? null : view.get();
}

public final void detachView() {
        if (view != null) {
            view.clear();
            view = null;
        }
        onViewDetached();
}`

**Comment by MaksTuev** [comment]
WeakReference is redundant, because reference to the view is cleared, when view is destroyed
